# Generated by Django 2.0.7 on 2018-07-29 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='article',
            field=models.TextField(default='Null'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comments',
            name='comment',
            field=models.TextField(default='Null'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='users',
            name='email',
            field=models.EmailField(default='Null', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='users',
            name='newsletter',
            field=models.BooleanField(default='False'),
            preserve_default=False,
        ),
    ]
